back/urls.py
from django.urls import path
from .views import nextPageView

# urlpatterns = [
# path('next/', nextPageView, name='next'),

]

face/urls.py
from django.urls import path
from .views import homePageView, newPageView, nextPageView


app_name='face'
urlpatterns = [
path('', homePageView, name='home'),
path('new/', newPageView, name='new'),
path('next/', nextPageView, name='next'),
]

lifeline/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('face.urls', namespace='face')),
    # path('', include('green.urls')),
]

back/models.py
from django.db import models

# 

face/models.py
from django.db import models

class Cover(models.Model):
    title = models.CharField(max_length=200)
    bar = models.CharField(max_length=200)
    cantact = models.CharField(max_length=200)  

    def __str__(self):
        return self.title

class Resources(models.Model):
    categories = models.CharField(max_length= 10)
        
    def __str__(self):
        return self.categories

class AboutUs(models.Model):
    history = models.CharField(max_length=1000)
    pillars = models.CharField(max_length=1000)
    hands = models.CharField(max_length=500)
    contact = models.CharField(max_length=200)

    def __str__ (self):
        return self.pillars

back/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import 

face/views.py
from django.shortcuts import render
from .models import Cover, Resources, AboutUs

def homePageView(request):
    cover = Cover.objects.all()
    

    context = {
        "cover":cover,
        
    }
    return render(request,'face/home.html' , context)

def newPageView(request):
    resources = Resources.objects.all()
    

    context = {
        "resources":resources,
        
    }
    return render(request,'face/new.html' , context)

def nextPageView (request):
    about_us = AboutUs.objects.all() 


    context = {
        "about_us":about_us
    } 
    return render(request,'face/next.html', context)

back/templates/green/next.html
{%extends "face/layout.html"%}
{%block content%}
   <h1 class="space-tag">This is the next page</h1>
   <h3>Here</h3>

   {% for tree in trees%}
     {{tree.quantity}}
     {{tree.title}}
   {%endfor%}
   
   <p>This is a another new page that i built</p>
{%endblock content%}

face/templates/face/home.html
{%extends "face/layout.html"%}
{%block content%}
       <h1 class="space-tag">it happened</h1>
       <h3>it happened</h3>

       {% for slide in slides%}
         {{slide.quantity}}
         {{slide.title}}
       {%endfor%}

       <p>Lorem, ipsum dolor sit amet consectetur
            adipisicing elit. Maxime, corrupti provident
             animi totam accusamus aperiam veritatis molestiae
              quod quia rerum, iusto enim? Iure nihil esse enim
               ab aliquid, necessitatibus perspiciatis.</p>

    <a href="">happened</a>
      <h1>it happened</h1>
{%endblock content%}

face/templates/face/layout.html
{%load static%}
<!DOCTYPE html>

[if gt IE 8]><--> <html class="no-js"> <![endif]
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'face/main.css'%}">
</head>
    <a href="{% url 'face:new'%}">New</a>
    <a href="{% url 'face:home'%}">home</a>
    <a href="{% url 'face:next'%}">next</a>
    
    
    <body>
        {%block content%} {%endblock content%}
        <script src="" async defer></script>
    </body>
</html>

face/templates/face/new.html
{%extends "face/layout.html"%}
{%block content%}
   <h1 class="space-tag">We are here</h1>
   <h3>Here</h3>

   {% for item in items%}
     {{item.quantity}}
     {{item.title}}
   {%endfor%}
   
   <p>This is a new page that i built</p>
{%endblock content%}